name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'   # Use 'temurin' or your preferred JDK
          java-version: '17'        # Use Java 17 or your project's Java version

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          ./gradlew clean build -x test  # Skips tests; remove `-x test` to include tests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Read and Increment Version
        id: version
        run: |
          
          if [ ! -f VERSION ]; then echo "v0.0.0" > VERSION; fi
          
          # Read the current version from the VERSION file
          version=$(cat VERSION)
          echo "Current version: $version"

          # Increment the patch version (v0.0.3 -> v0.0.4)
          new_version=$(echo "$version" | awk -F. -v OFS=. '{$NF += 1 ; print}')
          echo "New version: $new_version"

          # Update VERSION file with the new version and output it as an environment variable
          echo "$new_version" > VERSION
          echo "VERSION=$new_version" >> $GITHUB_ENV

      - name: Build Docker image with two tags
        run: |
          # Build and tag with both version number and latest
          docker build -t simsonmoses/spring-crud:${{ env.VERSION }} -t simsonmoses/spring-crud:latest .

      - name: Push Docker images to Docker Hub
        run: |
          # Push both the versioned tag and latest
          docker push simsonmoses/spring-crud:${{ env.VERSION }}
          docker push simsonmoses/spring-crud:latest

      - name: Prepare SSH Key
        run: |
          mkdir -p /home/runner/.ssh  # Explicitly create the .ssh directory
          echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/id_rsa  # Write the SSH key to id_rsa
          chmod 600 /home/runner/.ssh/id_rsa

      - name: SSH and Deploy on EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Deploying to EC2..."
            echo "host:"+host+" username:"+username
            cd /path/to/your/docker-compose
            docker-compose down
            docker-compose pull content-ms
            docker-compose up -d --no-deps content-ms
